import { ProColumns } from '@ant-design/pro-components';

export const columns: ProColumns<API.DataInfo>[] = [
  {
    title: 'locationid',
    dataIndex: 'locationid',
    copyable: true,
    width: 120,
  },
  {
    title: 'Applicant',
    dataIndex: 'Applicant',
    ellipsis: true,
    width: 220,
  },
  {
    title: 'FacilityType',
    dataIndex: 'FacilityType',
    width: 120,
  },
  {
    title: 'cnn',
    dataIndex: 'cnn',
  },
  {
    title: 'LocationDescription',
    dataIndex: 'LocationDescription',
    hideInSearch: true,
    ellipsis: true,
    width: 220,
  },
  {
    title: 'Address',
    dataIndex: 'Address',
    hideInSearch: true,
    width: 150,
  },
  {
    title: 'blocklot',
    dataIndex: 'blocklot',
    hideInSearch: true,
    width: 150,
  },
  {
    title: 'block',
    dataIndex: 'block',
    hideInSearch: true,
    width: 120,
  },
  {
    title: 'lot',
    dataIndex: 'lot',
    hideInSearch: true,
  },
  {
    title: 'permit',
    dataIndex: 'permit',
    hideInSearch: true,
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Status',
    dataIndex: 'Status',
    hideInSearch: true,
    ellipsis: true,
    width: 150,
  },
  {
    title: 'FoodItems',
    dataIndex: 'FoodItems',
    hideInSearch: true,
    ellipsis: true,
    width: 220,
  },
  {
    title: 'X',
    dataIndex: 'X',
    hideInSearch: true,
    width: 150,
  },
  {
    title: 'Y',
    dataIndex: 'Y',
    hideInSearch: true,
    width: 150,
  },
  {
    title: 'Latitude',
    dataIndex: 'Latitude',
    hideInSearch: true,
    width: 180,
  },
  {
    title: 'Longitude',
    dataIndex: 'Longitude',
    hideInSearch: true,
    width: 180,
  },
  {
    title: 'Schedule',
    dataIndex: 'Schedule',
    copyable: true,
    hideInSearch: true,
    ellipsis: true,
    width: 220,
  },
  {
    title: 'dayshours',
    dataIndex: 'dayshours',
    hideInSearch: true,
    width: 180,
  },
  {
    title: 'NOISent',
    dataIndex: 'NOISent',
    hideInSearch: true,
  },
  {
    title: 'Approved',
    dataIndex: 'Approved',
    hideInSearch: true,
    width: 180,
  },
  {
    title: 'Received',
    dataIndex: 'Received',
    hideInSearch: true,
    width: 180,
  },
  {
    title: 'PriorPermit',
    dataIndex: 'PriorPermit',
    hideInSearch: true,
    width: 120,
  },
  {
    title: 'ExpirationDate',
    dataIndex: 'ExpirationDate',
    hideInSearch: true,
    width: 220,
  },
  {
    title: 'Location',
    dataIndex: 'Location',
    hideInSearch: true,
    ellipsis: true,
    width: 220,
  },
  {
    title: 'Fire Prevention Districts',
    dataIndex: 'Fire Prevention Districts',
    hideInSearch: true,
    width: 220,
  },
  {
    title: 'Police Districts',
    dataIndex: 'Police Districts',
    hideInSearch: true,
    width: 220,
  },
  {
    title: 'Supervisor Districts',
    dataIndex: 'Supervisor Districts',
    hideInSearch: true,
    width: 220,
  },
  {
    title: 'Zip Codes',
    dataIndex: 'Zip Codes',
    hideInSearch: true,
    width: 120,
  },
  {
    title: 'Neighborhoods (old)',
    dataIndex: 'Neighborhoods (old)',
    hideInSearch: true,
    width: 150,
  },
];
